config-version: 1

# The root folder for the database change scripts
root-folder: '{{ env_var('GITHUB_WORKSPACE') }}/ci-cd-schemachange/scripts'

# The modules folder for jinja macros and templates to be used across multiple scripts.
modules-folder: null

# The name of the snowflake account (e.g. xy12345.east-us-2.azure)
snowflake-account: '{{ env_var('SF_ACCOUNT') }}'

# The name of the snowflake user
snowflake-user: '{{ env_var('SF_USERNAME') }}'

# The name of the default role to use.
snowflake-role: '{{ env_var('SF_ROLE') }}'

# The name of the default warehouse to use.
snowflake-warehouse: '{{ env_var('SF_WAREHOUSE') }}'

# The name of the default database to use.
snowflake-database: '{{ env_var('SF_DATABASE') }}'

# Used to override the default name of the change history table
change-history-table: '{{ env_var('SF_DATABASE') }}.SCHEMACHANGE.CHANGE_HISTORY'

# Define values for the variables to replaced in change scripts
vars:
  environment_name: '{{ env_var('ENVIRONMENT_NAME').lower() }}'
  end_of_file_statement: 'USE ROLE {{ env_var('SF_ROLE') }};'
  database_name_prefix: '{{ env_var('DATABASE_NAME_PREFIX') }}'
  region: '{{ env_var('REGION') }}'

# Create the change history schema and table, if they do not exist
create-change-history-table: true

# Enable autocommit feature for DML commands
autocommit: false

# Display verbose debugging details during execution
verbose: true

# Run schemachange in dry run mode
dry-run: false