name: Reusable SchemaChange Job

on:
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string
      env_prefix:
        required: true
        type: string
      warehouse:
        required: true
        type: string
      database:
        required: true
        type: string
      role:
        required: true
        type: string
      schema_change_flags:
        required: true
        type: string
    secrets:
      SF_PRIVATE_KEY:
        required: true
      SF_KEY_PASSPHRASE:
        required: true

jobs:
  deploy:
    name: Deploy SchemaChange Changes to ${{ inputs.target_env }}
    environment: ${{ inputs.target_env }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.3.4
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: rwb73287.us-east-1
          SF_USERNAME: SVC_SCHEMACHANGE
          SF_ROLE: ${{ inputs.role }}
          SF_WAREHOUSE: ${{ inputs.warehouse }}
          SF_DATABASE: ${{ inputs.database }}
          REGION: us-east-1
          ENVIRONMENT_NAME: ${{ inputs.target_env }}
          DATABASE_NAME_PREFIX: ${{ inputs.env_prefix }}_
          SNOWFLAKE_PRIVATE_KEY_PATH: ${{ github.workspace }}/sf_schemachange_private_key.p8
          SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SF_KEY_PASSPHRASE }}
        run: |
          echo "${{ secrets.SF_PRIVATE_KEY }}" > sf_schemachange_private_key.p8
          pip install schemachange==3.7.0
          cd $GITHUB_WORKSPACE/ci-cd-schemachange
          schemachange ${{ inputs.schema_change_flags }}
